"""initial schema

Revision ID: 4a0ca35fda6f
Revises: 
Create Date: 2026-08-21 21:02:15.277539

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '4a0ca35fda6f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_usage',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('role', sa.String(length=48), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('tofu_task_id', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_usage_run_id'), ['run_id'], unique=False)

    op.create_table('term_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term_id', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('term_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_term_audit_log_term_id'), ['term_id'], unique=False)

    op.create_table('terms',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_term', sa.String(length=256), nullable=False),
    sa.Column('preferred_target', sa.String(length=512), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_terms_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_terms_source_term'), ['source_term'], unique=False)

    op.create_table('translation_memory',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=True),
    sa.Column('domain', sa.String(length=64), nullable=True),
    sa.Column('source_document', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('authority', sa.String(length=32), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('score_hint', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('translation_memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translation_memory_authority'), ['authority'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_memory_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_memory_domain'), ['domain'], unique=False)

    op.create_table('translation_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('confidentiality', sa.String(length=16), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('current_stage', sa.String(length=32), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('loop_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('pipeline_version', sa.String(length=32), nullable=False),
    sa.Column('version_pins', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('translation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translation_runs_status'), ['status'], unique=False)

    op.create_table('document_glossaries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('entries', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['translation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_glossaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_glossaries_run_id'), ['run_id'], unique=False)

    op.create_table('run_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('segment_ids', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['translation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_events_run_id'), ['run_id'], unique=False)

    op.create_table('segments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('versions', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['translation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_segments_run_id'), ['run_id'], unique=False)

    op.create_table('term_evidence',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('term_id', sa.String(length=32), nullable=False),
    sa.Column('source_document', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('authority', sa.String(length=32), nullable=False),
    sa.Column('source_sentence', sa.Text(), nullable=True),
    sa.Column('target_sentence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('term_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_term_evidence_term_id'), ['term_id'], unique=False)

    op.create_table('term_variants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('term_id', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('term_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_term_variants_term_id'), ['term_id'], unique=False)

    op.create_table('issues',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('segment_id', sa.String(length=32), nullable=True),
    sa.Column('reviewer', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('source_span', sa.Text(), nullable=True),
    sa.Column('target_span', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['translation_runs.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issues_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_run_id'))

    op.drop_table('issues')
    with op.batch_alter_table('term_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_term_variants_term_id'))

    op.drop_table('term_variants')
    with op.batch_alter_table('term_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_term_evidence_term_id'))

    op.drop_table('term_evidence')
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_segments_run_id'))

    op.drop_table('segments')
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_events_run_id'))

    op.drop_table('run_events')
    with op.batch_alter_table('document_glossaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_glossaries_run_id'))

    op.drop_table('document_glossaries')
    with op.batch_alter_table('translation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_runs_status'))

    op.drop_table('translation_runs')
    with op.batch_alter_table('translation_memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_memory_domain'))
        batch_op.drop_index(batch_op.f('ix_translation_memory_document_type'))
        batch_op.drop_index(batch_op.f('ix_translation_memory_authority'))

    op.drop_table('translation_memory')
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_terms_source_term'))
        batch_op.drop_index(batch_op.f('ix_terms_domain'))

    op.drop_table('terms')
    with op.batch_alter_table('term_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_term_audit_log_term_id'))

    op.drop_table('term_audit_log')
    with op.batch_alter_table('model_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_usage_run_id'))

    op.drop_table('model_usage')
    # ### end Alembic commands ###
