"""corpus tables

Revision ID: a45ac689115a
Revises: 4a0ca35fda6f
Create Date: 2026-08-21 22:51:10.810160

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'a45ac689115a'
down_revision: str | Sequence[str] | None = '4a0ca35fda6f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpus_documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=True),
    sa.Column('domain', sa.String(length=64), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('structure', sa.JSON(), nullable=False),
    sa.Column('doc_metadata', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corpus_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corpus_documents_content_hash'), ['content_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_corpus_documents_url'), ['url'], unique=False)

    op.create_table('document_pairs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('zh_doc_id', sa.String(length=32), nullable=False),
    sa.Column('en_doc_id', sa.String(length=32), nullable=False),
    sa.Column('match_method', sa.String(length=32), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['en_doc_id'], ['corpus_documents.id'], ),
    sa.ForeignKeyConstraint(['zh_doc_id'], ['corpus_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aligned_pairs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('pair_id', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('idx', sa.String(length=32), nullable=False),
    sa.Column('zh_text', sa.Text(), nullable=False),
    sa.Column('en_text', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tm_entry_id', sa.String(length=32), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['pair_id'], ['document_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aligned_pairs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aligned_pairs_pair_id'), ['pair_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aligned_pairs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aligned_pairs_pair_id'))

    op.drop_table('aligned_pairs')
    op.drop_table('document_pairs')
    with op.batch_alter_table('corpus_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corpus_documents_url'))
        batch_op.drop_index(batch_op.f('ix_corpus_documents_content_hash'))

    op.drop_table('corpus_documents')
    # ### end Alembic commands ###
