"""style rules

Revision ID: c7d635216dda
Revises: 9ebe5c38164a
Create Date: 2026-08-21 23:40:52.063719

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'c7d635216dda'
down_revision: str | Sequence[str] | None = '9ebe5c38164a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style_rules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('rule', sa.Text(), nullable=False),
    sa.Column('zh_pattern', sa.String(length=256), nullable=False),
    sa.Column('en_rendering', sa.String(length=512), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=False),
    sa.Column('counterexamples', sa.JSON(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('domains', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('style_rules')
    # ### end Alembic commands ###
